#!/bin/bash

## Shows that must be dealt with
#American Indian Living
#Bible Talk
#Education Currents
#Health and Longevity
#Healthy By Choice
#Healthy By Choice
#Heartwise Ministries
#Homeschool Companion
#LifeQuest - Authors
#LifeQuest - Love For a Lifetime
#LifeQuest Liberty
#Message of Hope
#Sink The Beagle
#Someone Cares Prision Ministry

## filetypes ignore case
# mp3
# mp2
# wav
# aif
# docx
# doc

declare -A src_dir_array

project_dir="/var/projects/ltr_podcasts"

script_dir="/var/projects/ltr_podcasts/scripts"

logs_dir="/var/projects/ltr_podcasts/scripts/logs/convert"

script_name=$(basename "$0")
logfile="${logs_dir}/${script_name}_$(date +%Y%m%d_%H%M).log"
touch $logfile

## This would be changed to the download directory after testing
#parent_dir="${project_dir}/testing"
parent_dir="${project_dir}/downloads"
converted_dest_dir="${project_dir}/converted"

inc_pattern="^.*\.(mp3|mp2|wav|docx|doc|aif|MP3|MP2|WAV|DOCX|DOC|AIF)$"

skipped_file="${logs_dir}/skipped"

if [[ -f "$skipped_file" ]]; then
    mv "$skipped_file" "${skipped_file}_$(date +%Y%m%d_%H%M)"
fi

touch "$skipped_file"

echo -e "**** $(date +%Y%m%d_%H%M) ****" >> "$skipped_file"

expected_file="${logs_dir}/expected"

if [[ -f "$expected_file" ]]; then
    mv "$expected_file" "${expected_file}_$(date +%Y%m%d_%H%M)"
fi

touch "$expected_file"

echo -e "**** $(date +%Y%m%d_%H%M) ****" >> "$expected_file"

copied_file="${logs_dir}/copied"

if [[ -f "$copied_file" ]]; then
    mv "$copied_file" "${copied_file}_$(date +%Y%m%d_%H%M)"
fi

touch "$copied_file"

echo -e "**** $(date +%Y%m%d_%H%M) ****" >> "$copied_file"

## Double hashes are converted
## AIL had major conversion errors coming from ffmpeg. Further investigation needed
#src_dir_array[ail]="American Indian Living"
##src_dir_array[bt]="Bible Talk"
##src_dir_array[ec]="Education Currents"
##src_dir_array[hal]="Health and Longevity"
##src_dir_array[hbc]="Healthy By Choice"
##src_dir_array[hm]="Heartwise Ministries"
##src_dir_array[hc]="Homeschool Companion"
src_dir_array[lqa]="LifeQuest - Authors"
## Not required #src_dir_array[lqlfal]="LifeQuest - Love For a Lifetime"
##src_dir_array[lql]="LifeQuest Liberty"
##src_dir_array[moh]="Message of Hope"
##src_dir_array[stb]="Sink The Beagle"
##src_dir_array[scpm]="Someone Cares Prison Ministry"

skip_file() {
    # Arguments:
    # $1 -> $src_file
    # $2 -> $skipped_reason
    #    one of: src not found | dest exists | bad filename | bad filetype
    src_file="$1"
    skipped_reason="$2"
    #echo "skip_file()"

    echo "Skipping..."
    echo "[$skipped_reason] $src_file"  >>  "$skipped_file"

}

get_filetype() {
    # Arguements:
    # 1 -> src_file
    src_file="$1"
    
    #echo "get_filetype() - src_file is $src_file"

    ## Does the filename contain a dot?
    if [[ -f "$src_file" ]]; then
        if [[ $src_file == *\.* ]]; then
            file_extension=$(echo "$src_file" | awk 'BEGIN{FS=OFS="."}{ print $(NF) }')
        
        else
            echo "$src_file doesn't seem to have a normal '.ext' file extension"
            skip_file "$src_file" "bad filename"
        fi
    else
        echo "$src_file doesn't seem to exist"
        skip_file "$src_file" "src not found"
    fi
}

get_output_file() {

    #echo "get_output_file() - "
    if [[ -f "$src_file" ]]; then
        if [[ $src_file == *\.* ]]; then
            #echo "$src_file" | awk 'BEGIN{FS=OFS="."}{ NF--; print }'

            ######################################
            #### BEGIN file_name manipulation ####
            ######################################
            ## split on '/' and take only the last field
            org_file_name="$(echo "$src_file" | awk 'BEGIN{FS=OFS="/"}{ print $(NF) }')"
            
            ## trim commas out 
            org_file_name="$(echo "$org_file_name" | tr ',' ' ')"

            ## split on '.', remove the final field (hopefully the .ext), take the last field (prev. 2nd to last) and add '.mp3'
            file_name="$(echo "$src_file" | awk 'BEGIN{FS=OFS="."}{ NF--; print }' | awk 'BEGIN{FS=OFS="/"}{ print $(NF) ".mp3" }')"
            
            ## trim commas out
            file_name="$(echo "$file_name" | tr ',' ' ')"

            # en dash
            # tr had trouble outputing weird characters with the en dash replacement
            file_name="$(echo "$file_name" | sed -e "s/–/\ /g")"

            # acute accent ´
            # left single quote mark ‘
            # right single quote mark ’
            # single high reversed 9 quote mark ‛
            # prime ′
            # reversed prime ‵
            ## cannot  make tr or sed deal with backtick\grave accent properly
            # grave accent `

            # singles
            file_name="$(echo "$file_name" | sed -e "s/´/\ /g")"
            file_name="$(echo "$file_name" | sed -e "s/'/\ /g")"
            file_name="$(echo "$file_name" | sed -e "s/‘/\ /g")"
            file_name="$(echo "$file_name" | sed -e "s/’/\ /g")"
            file_name="$(echo "$file_name" | sed -e "s/‛/\ /g")"
            file_name="$(echo "$file_name" | sed -e "s/′/\ /g")"
            file_name="$(echo "$file_name" | sed -e "s/‵/\ /g")"

            # double acute accent ˝
            # left double quote mark “
            # right double quote mark ”
            # doulbe high-reversed-9 quote mark ‟
            # double prime ″
            # reveresed double prime ‶
            
            # doubles
            file_name="$(echo "$file_name" | sed -e 's/˝/\ /g')"
            file_name="$(echo "$file_name" | sed -e 's/“/\ /g')"
            file_name="$(echo "$file_name" | sed -e 's/”/\ /g')"
            file_name="$(echo "$file_name" | sed -e 's/‟/\ /g')"
            file_name="$(echo "$file_name" | sed -e 's/″/\ /g')"
            file_name="$(echo "$file_name" | sed -e 's/‶/\ /g')"

            ## replace uppercase to lowercase
            file_name="$(echo "$file_name" | tr '[:upper:]' '[:lower:]')"
            
            ## replaced " - " with " ", sometimes many times in a filename
            file_name="$(echo "$file_name" | sed -e 's/\ -\ /\ /g')"
            #file_name="$(echo "$file_name" | sed -e 's/\ -\ /\ /')"
            #file_name="$(echo "$file_name" | sed -e 's/\ -\ /\ /')"
            #file_name="$(echo "$file_name" | sed -e 's/\ -\ /\ /')"

            ## remove dashes
            file_name="$(echo "$file_name" | sed -e 's/-/\ /g')"

            ## remove '.' not before 'm's 
            file_name="$(echo "$file_name" | sed -e 's/\.[^m]//g')"

            ## replace '.m.' with 'm', to leave .mp3 alone
            file_name="$(echo "$file_name" | sed -e 's/\.m\./m/g')"

            ## remove _(ok|final|remixed)
            file_name="$(echo "$file_name" | sed -e 's/\_final//')"
            #file_name="$(echo "$file_name" | sed -e 's/\_remixed//')"
            file_name="$(echo "$file_name" | sed -e 's/\_ok//')"

            ## remove \ (final|ok|remixed). with '.'
            file_name="$(echo "$file_name" | sed -e 's/\ final\./\./')"
            #file_name="$(echo "$file_name" | sed -e 's/\ remixed\./\./')"
            file_name="$(echo "$file_name" | sed -e 's/\ ok\./\./')"

            ## replace -{2,} with ' '
            file_name="$(echo "$file_name" | sed -e 's/-\{2,\}/ /g')"

            ## remove ,
            file_name="$(echo "$file_name" | sed -e 's/,//g')"

            ## replace \ {2,} with single ' '
            file_name="$(echo "$file_name" | sed -e 's/\ \{2,\}/ /g')"
            
            ## translate space to underscore
            file_name="$(echo "$file_name" | tr ' ' '_')"
        
            ## replace _{2,} with '_' 
            file_name="$(echo "$file_name" | sed -e 's/_\{2,\}/_/g')"
            #file_name="$(echo "$file_name" | sed -e 's/__\+/_/')"

            #### END file_name manipulation ####

            ######################################
            #### BEGIN dest. dir manipuation  ####
            ######################################
            old_file_sub_path="$(echo "$src_file" | awk 'BEGIN{FS=OFS="/"}{NF--; print }' | cut -d/ -f6- )"
            file_sub_path="$(echo "$src_file" | awk 'BEGIN{FS=OFS="/"}{NF--; print }' | cut -d/ -f7- )"
            file_sub_path="$key/$file_sub_path"

            ## trim commas out
            file_sub_path="$(echo "$file_sub_path" | tr ',' ' ')"
            
            ## trim en dash out
            file_sub_path="$(echo "$file_sub_path" | tr '–' ' ')"
            
            ## replace uppercase to lowercase
            file_sub_path="$(echo "$file_sub_path" | tr '[:upper:]' '[:lower:]')"
            
            ## replaced " - " with " ", sometimes many times in a filename
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/\ -\ /\ /g')"
            #file_sub_path="$(echo "$file_sub_path" | sed -e 's/\ -\ /\ /')"
            #file_sub_path="$(echo "$file_sub_path" | sed -e 's/\ -\ /\ /')"
            #file_sub_path="$(echo "$file_sub_path" | sed -e 's/\ -\ /\ /')"

            ## remove dashes
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/-/\ /g')"

            # en dash
            # tr had trouble outputing weird characters with the en dash replacement
            file_sub_path="$(echo "$file_sub_path" | sed -e "s/–/\ /g")"

            # acute accent ´
            # left single quote mark ‘
            # right single quote mark ’
            # single high reversed 9 quote mark ‛
            # prime ′
            # reversed prime ‵
            ## cannot  make tr or sed deal with backtick\grave accent properly
            # grave accent `

            # singles
            file_sub_path="$(echo "$file_sub_path" | sed -e "s/´/\ /g")"
            file_sub_path="$(echo "$file_sub_path" | sed -e "s/'/\ /g")"
            file_sub_path="$(echo "$file_sub_path" | sed -e "s/‘/\ /g")"
            file_sub_path="$(echo "$file_sub_path" | sed -e "s/’/\ /g")"
            file_sub_path="$(echo "$file_sub_path" | sed -e "s/‛/\ /g")"
            file_sub_path="$(echo "$file_sub_path" | sed -e "s/′/\ /g")"
            file_sub_path="$(echo "$file_sub_path" | sed -e "s/‵/\ /g")"

            # double acute accent ˝
            # left double quote mark “
            # right double quote mark ”
            # doulbe high-reversed-9 quote mark ‟
            # double prime ″
            # reveresed double prime ‶
            
            # doubles
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/˝/\ /g')"
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/“/\ /g')"
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/”/\ /g')"
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/‟/\ /g')"
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/″/\ /g')"
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/‶/\ /g')"

            ## remove '.' not before 'm's 
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/\.[^m]//g')"

            ## replace '.m.' with 'm', to leave .mp3 alone
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/\.m\./m/g')"

            ## remove _(ok|final|remixed)
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/\_final//')"
            #file_sub_path="$(echo "$file_sub_path" | sed -e 's/\_remixed//')"
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/\_ok//')"

            ## remove \ (final|ok|remixed). with '.'
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/\ final\./\./')"
            #file_sub_path="$(echo "$file_sub_path" | sed -e 's/\ remixed\./\./')"
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/\ ok\./\./')"

            ## replace -{2,} with ' '
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/-\{2,\}/ /g')"

            ## remove ,
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/,//g')"

            ## replace \ {2,} with single ' '
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/\ \{2,\}/ /g')"
            
            ## translate space to underscore
            file_sub_path="$(echo "$file_sub_path" | tr ' ' '_')"
        
            ## replace _{2,} with '_' 
            file_sub_path="$(echo "$file_sub_path" | sed -e 's/_\{2,\}/_/g')"

            #### END dest. dir manipuation  ####

            #echo "src_file: $src_file"
            #echo "old_sub_path: $old_file_sub_path"
            #echo "sub_path: $file_sub_path"

            filetype="$file_extension"

            converted_path="$converted_dest_dir/$file_sub_path"
            converted_filepath="$converted_path/$file_name"
            
            echo "$converted_filepath" >> "$expected_file"

            if ! [[  -d "$converted_path" ]]; then
                mkdir -p "$converted_path";
            fi
            
        else
            echo "$src_file doesn't seem to have a normal '.ext' file extension"
            skip_file "$src_file" "bad filename"
        fi
    else
        echo "$src_file doesn't seem to exist"
        skip_file "$src_file" "src not found"
    fi
    

}

get_bitrate() {
    # Arguements:
    # 1 -> src_file
    # 2 -> file_name
    # 3 -> file_extension
    src_file="$1"
    file_name="$2"
    file_extension="$3"
    ffprobe "$src_file" 2>&1 | grep Stream | cut -d "," -f5 | cut -d" " -f2

}

copy_to_dest() {
    # Arguments:
    # 1 -> src_file
    # 2 -> file_name
    # 3 -> file_extension
    src_file="$1"
    file_name="$2"
    file_extension="$3"
    
    echo "copy_to_dest() -"

    get_output_file "$src_file"
    echo "COPYING: $src_file to $converted_filepath"

    cp "$src_file" "$converted_filepath"
    echo "$src_file" >> "$copied_file"

}

convert_bitrate() {
    # Arguements:
    # 1 -> src_file
    # 2 -> file_name
    # 3 -> file_extension
    src_file="$1"
    file_name="$2"
    file_extension="$3"

    ## For a file that is already mp3 but the wrong bitrate
    #echo "convert_bitrate()"
    #echo "src_file: $src_file"

    #echo "convert_bitrate() - "
    get_output_file "$src_file"
    
    #echo "test: fake converting bit rate"
    #echo "would write $converted_filepath"
    ffmpeg -loglevel error -nostdin -y -i "$src_file" -codec:a libmp3lame -b:a 96k -map a "$converted_filepath" >> $logfile 2>&1    

}

convert_to_mp3() {
    # Arguements:
    # 1 -> src_file
    # 2 -> file_name
    # 3 -> file_extension
    src_file="$1"
    file_name="$2"
    file_extension="$3"

    #echo "convert_to_mp3() -"
    #echo "file_name:$file_name"
    #echo "file_extension:$file_extension"
    #echo "converted_filepath:$converted_filepath"

    get_output_file "$src_file"
    
    #echo "test: fake convert $file_extension to MP3"
    #echo "would write $converted_filepath"


    ffmpeg -loglevel error -nostdin -y -i "$src_file" -codec:a libmp3lame -b:a 96k -map a "$converted_filepath" >> $logfile 2>&1 

}

check_files() {
    # Arguments:
    # 1 -> src_dir
    src_dir="$1"
    key="$2"
    #echo "check_files() - src_dir is $src_dir"

    find "$src_dir" -type f -print0 |
      while IFS= read -r -d $'\0' src_file; do
          #echo "check_files() - src_file $src_file"
         
          unset converted_filepath

          #echo "check_files() - (should be empty): $converted_filepath"
          
          get_output_file "$src_file"
          
          #echo "check_files() - $converted_filepath"
          

          if [[ -f "$converted_filepath" ]]; then

              echo "$converted_filepath already exists"
              skip_file "$src_file" "dest exists"

          else
              
              #echo "check_files() - doesn't exist: $converted_filepath"
              
              get_filetype "$src_file"
              
              #echo "$org_file_name is $file_extension"

              case "$file_extension" in
                    mp3)
                        cur_bitrate=$(get_bitrate "$src_file")
                        #echo "bitrate is $cur_bitrate"
                        
                        if [[ "$cur_bitrate" != 96 ]]; then
                            #echo "MP3 but bitrate bad, must change bitrate"
                            convert_bitrate "$src_file" "$file_name" "$file_extension"
                        else
                            echo "bitrate OK"
                            copy_to_dest "$src_file" "$file_name" "$file_extension"
                        fi
                        ;;
                    aif|wav)
                        #echo "not mp3"
                        #echo "must convert to MP3"
                        convert_to_mp3 "$src_file" "$file_name" "$file_extension"
                        ;;
                    *)
                        #echo "filetype '$file_extension' unknown"
                        #echo "Skipping $src_file"
                        skip_file "$src_file" "bad filetype"
                        ;;
              esac
        fi

    done

}



main() {
echo -e "**** $(date +%Y%m%d_%H%M) ****" >> "$logfile"
echo -e "**** Start of script ****" >> "$logfile"
echo -e "ffmpeg loglevel set to ''errors only''"
echo -e "do not expect further status updates until end of script"
echo -e "Looking at these source directories:" >> "$logfile"

for key in "${!src_dir_array[@]}"; do
    src_dir="${src_dir_array[$key]}"
    echo "$src_dir" >> "$logfile"
done

for key in "${!src_dir_array[@]}"; do
    src_dir="${src_dir_array[$key]}"

    src_dir="$parent_dir/$src_dir/"

    if [[ -d "$src_dir" ]]; then
        echo "main() - src_dir is $src_dir";

        check_files "$src_dir" "$key";
    else
        echo "main() - scr_dir as ''$src_dir'' is not valid"
    fi
done

    ## get_out_file() is writing the $converted_filepath to $expected_log
    ## that we would use a list to check the actual files that are created 
    ## against. However, check_files() currently calling that subroutine
    ## in order to get $converted_filepath for a test; this results in two lines
    ## written to the log file
    ## using a uniq statement to account for this

echo "**** Skipped files ****"
cat "$skipped_file"
#echo "**** Expected files ****"
#cat "$expected_file"


## This should work? Works in a test file. 
## No idea why found_count remains null
#while IFS='' read -r line; do
#    echo "FOUNDCOUNT $found_count"
#    found_count=0
#    if ! [[ $line =~ "****" ]]; then
#        if [[ -f "$line" ]]; then
#            ((found_count++))
#        else
#            echo "ERROR: did not find -- $line" >> $logfile
#        fi
#    fi
#    
#done < "$expected_file"
#expected_num=$(cat $expected_file | grep -v "\*" | uniq | wc -l)
#
#
#echo "Expected number of files: $expected_num"
#echo "Found number of files: $found_count"
#
#if [[ $expected_num != $found_count ]]; then
#    echo "Did not find the expected number of converted files. Please check the log: $logfile"
#fi

}

main

echo -e "**** End of script ****" >> "$logfile"
echo -e "**** $(date +%Y%m%d_%H%M) ****" >> "$logfile"

## Put files to S3


