#!/bin/bash

## Get files from ftp

# lftp mirror -c --include RX SOURCE

## where RX like ''^.*\.(wav|mp3|docx)$''
## may be better an exclude?
## -c is continue if possible
## Source one of
#American Indian Living
#Bible Talk
#Education Currents
#Health and Longevity
#Healthy By Choice
#Healthy By Choice
#Heartwise Ministries
#Homeschool Companion
#LifeQuest - Authors
#LifeQuest - Love For a Lifetime
#LifeQuest Liberty
#Message of Hope
#Sink The Beagle
#Someone Cares Prision Ministry

## filetypes ignore case
# mp3
# mp2
# wav
# aif
# docx
# doc

declare -A src_dir_array

script_name="$(basename "$0")"

project_dir="/var/projects/ltr_podcasts"

script_dir="/var/projects/ltr_podcasts/scripts"

logs_dir="/var/projects/ltr_podcasts/scripts/logs/download"


logfile="${logs_dir}/${script_name}"

if [[ -f "$logfile" ]]; then
    rm "$logfile"
fi
touch $logfile

echo -e "**** $(date +%Y%m%d_%H%M) ****" >> "$logfile"


src_server="ftp.lifetalk.net"
dest_dir="/var/projects/ltr_podcasts/downloads/"
inc_pattern="^.*\.(mp3|mp2|wav|aif|MP3|MP2|WAV|AIF)$"

#src_dir_array[ail]="American Indian Living"
#src_dir_array[bt]="Bible Talk"
#src_dir_array[ec]="Education Currents"
#src_dir_array[hal]="Health and Longevity"
#src_dir_array[hbc]="Healthy By Choice"
#src_dir_array[hm]="Heartwise Ministries"
#src_dir_array[hc]="Homeschool Companion"
#src_dir_array[lqa]="LifeQuest - Authors"
#src_dir_array[lqlfal]="LifeQuest - Love For a Lifetime"
#src_dir_array[lql]="LifeQuest Liberty"
#src_dir_array[moh]="Message of Hope"
#src_dir_array[stb]="Sink The Beagle"
#src_dir_array[scpm]="Someone Cares Prison Ministry"

for src_dir in "${src_dir_array[@]}"; do
    echo "Source directory selected: $src_dir";
    #lftp -c "open ${src_server}; ls /${src_dir}";
    #lftp -c "debug; open ${src_server}; get \"/${src_dir}/BT001.mp3\" -o ${dest_dir}"
    #lftp -c "debug 3; open ${src_server}; mirror -P 5 --dry-run -v --include \"${inc_pattern}\" \"/${src_dir}\" \"${dest_dir}\""
    lftp -c "debug 2; open ${src_server}; mirror --log=\"${logfile}\" -P 10 -v --include \"${inc_pattern}\" \"/${src_dir}\" \"${dest_dir}\"" >> ${logfile} 2>&1
done

## Convert files to BITRATE

## Manipulate the filenames (lowercase, etc.)

## Put files to S3


