#!/bin/bash

declare -A src_dir_array
declare -a skipped_files_array

script_name=$(basename "$0")
logfile="/var/projects/ltr_podcasts/logs/${script_name}_$(date +%Y%m%d_%H%M).log"

## This would be changed to the download directory after testing
#parent_dir="/var/projects/ltr_podcasts/testing"
parent_dir="/var/projects/ltr_podcasts/downloads"
converted_dest_dir="/var/projects/ltr_podcasts/converted/"

inc_pattern="^.*\.(mp3|mp2|wav|docx|doc|aif|MP3|MP2|WAV|DOCX|DOC|AIF)$"

if [[ -d "./csv" ]]; then
    mkdir -p "./csv"
fi

csv_outfile="./csv/csv_outfile.csv"

if [[ -e "$csv_outfile" ]]; then
    mv "$csv_outfile" "${csv_outfile}_$(date +%Y%m%d_%H%M)"
fi

touch "$csv_outfile"

## Add headers to csv_outfile
echo -e "**** $(date +%Y%m%d_%H%M) ****\norg_file_name,(new) file_name,path" >> "$csv_outfile"

src_dir_array[ail]="American Indian Living"
src_dir_array[bt]="Bible Talk"
src_dir_array[ec]="Education Currents"
src_dir_array[hal]="Health and Longevity"
src_dir_array[hbc]="Healthy By Choice"
src_dir_array[hm]="Heartwise Ministries"
src_dir_array[hc]="Homeschool Companion"
src_dir_array[lqa]="LifeQuest - Authors"
src_dir_array[lqlfal]="LifeQuest - Love For a Lifetime"
src_dir_array[lql]="LifeQuest Liberty"
src_dir_array[moh]="Message of Hope"
src_dir_array[stb]="Sink The Beagle"
src_dir_array[scpm]="Someone Cares Prison Ministry"



get_output_file() {

    #echo "get_output_file() - "
    if [[ -f "$src_file" ]]; then
        if [[ $src_file == *\.* ]]; then
            #echo "$src_file" | awk 'BEGIN{FS=OFS="."}{ NF--; print }'

            ## split on '/' and take only the last field
            org_file_name="$(echo "$src_file" | awk 'BEGIN{FS=OFS="/"}{ print $(NF) }')"
            
            ## trim commas out 
            org_file_name="$(echo "$org_file_name" | tr ',' ' ')"

            ## split on '.', remove the final field (hopefully the .ext), take the last field (prev. 2nd to last) and add '.mp3'
            file_name="$(echo "$src_file" | awk 'BEGIN{FS=OFS="."}{ NF--; print }' | awk 'BEGIN{FS=OFS="/"}{ print $(NF) ".mp3" }')"
            
            ## trim commas out
            file_name="$(echo "$file_name" | tr ',' ' ')"
            
            file_sub_path="$(echo "$src_file" | awk 'BEGIN{FS=OFS="/"}{NF--; print }' | cut -d/ -f6- )"
            
            ## replace uppercase to lowercase
            file_name="$(echo "$file_name" | tr '[:upper:]' '[:lower:]')"
            
            ## replaced " - " with " ", sometimes many times in a filename
            file_name="$(echo "$file_name" | sed -e 's/\ -\ /\ /')"
            file_name="$(echo "$file_name" | sed -e 's/\ -\ /\ /')"
            file_name="$(echo "$file_name" | sed -e 's/\ -\ /\ /')"
            file_name="$(echo "$file_name" | sed -e 's/\ -\ /\ /')"
            
            ## remove _(ok|final|remixed)

            file_name="$(echo "$file_name" | sed -e 's/\_final//')"
            #file_name="$(echo "$file_name" | sed -e 's/\_remixed//')"
            file_name="$(echo "$file_name" | sed -e 's/\_ok//')"

            ## remove \ (final|ok|remixed). with '.'
            file_name="$(echo "$file_name" | sed -e 's/\ final\./\./')"
            #file_name="$(echo "$file_name" | sed -e 's/\ remixed\./\./')"
            file_name="$(echo "$file_name" | sed -e 's/\ ok\./\./')"

            ## replace -{2,} with ' '
            file_name="$(echo "$file_name" | sed -e 's/-\{2,\}/ /')"

            ## remove ,
            file_name="$(echo "$file_name" | sed -e 's/,//')"

            ## replace \ {2,} with single ' '
            file_name="$(echo "$file_name" | sed -e 's/\ \{2,\}/ /')"
            
            ## translate space to underscore
            file_name="$(echo "$file_name" | tr ' ' '_')"
        
            ## replace _{2,} with '_' 
            file_name="$(echo "$file_name" | sed -e 's/_\{2,\}/_/')"
            

            echo "${org_file_name},${file_name},${file_sub_path}" >> "$csv_outfile"


            filetype="$file_extension"

            converted_path="$converted_dest_dir$file_sub_path"
            converted_filepath="$converted_path/$file_name.mp3"

            if ! [[  -d "$converted_path" ]]; then
                mkdir -p "$converted_path";
            fi
            
        fi
    fi

}

check_files() {
    # Arguments:
    # 1 -> src_dir
    src_dir="$1"
    #echo "check_files() - src_dir is $src_dir"

    find "$src_dir" -type f -print0 |
      while IFS= read -r -d $'\0' src_file; do
          
          get_output_file "$src_file"
    done
}
main() {


for key in "${!src_dir_array[@]}"; do
    src_dir="${src_dir_array[$key]}"

    src_dir="$parent_dir/$src_dir/"

    if [[ -d "$src_dir" ]]; then
        echo "main() - src_dir is $src_dir";

        check_files "$src_dir";
    else
        echo "main() - scr_dir as ''$src_dir'' is not valid"
    fi
done
echo "final count: $count"
echo "These files were skipped: ${skipped_files_array[@]}"
}


main


