#!/bin/bash

project_dir="/var/projects/ltr_podcasts"

script_dir="/var/projects/ltr_podcasts/scripts"

logs_dir="/var/projects/ltr_podcasts/scripts/logs/upload"

script_name=$(basename "$0")

converted_dir="${project_dir}/converted"

inc_pattern="^.*\.(mp3|mp2|wav|docx|doc|aif|MP3|MP2|WAV|DOCX|DOC|AIF)$"


## In order to generate logs for each show during a single script execution
## the primary log config happens within main()

expected_file="${logs_dir}/expected"
if [[ -f "$expected_file" ]]; then
    mv "$expected_file" "${expected_file}_$(date +%Y%m%d_%H%M)"
fi
#touch "$expected_file"
#echo -e "**** $(date +%Y%m%d_%H%M) ****" >> "$expected_file"

copied_file="${logs_dir}/copied"
if [[ -f "$copied_file" ]]; then
    mv "$copied_file" "${copied_file}_$(date +%Y%m%d_%H%M)"
fi
#touch "$copied_file"
#echo -e "**** $(date +%Y%m%d_%H%M) ****" >> "$copied_file"

declare -A dir_array
## Comment/uncomment these to select which directors the script will run on 
## i.e. to select which shows to upload or not

#dir_array[ail]="ail" #"American Indian Living"
#dir_array[bt]="bt" #"Bible Talk"
#dir_array[ec]="ec" #"Education Currents"
dir_array[hal]="hal" #"Health and Longevity"
#dir_array[hbc]="hbc" #"Healthy By Choice"
## chip shouldn't need to be explicitly run because it's already
## a sub folder of hbc
#dir_array[chip]="hbc/chip_health" #"Healthy By Choice"
#dir_array[hm]="hm" #"Heartwise Ministries"
#dir_array[hc]="hc" #"Homeschool Companion"
#dir_array[lqa]="lqa" #"LifeQuest - Authors"
## LQLFAL is not needed
#dir_array[lql]="lql" #"LifeQuest Liberty"
#dir_array[moh]="moh" #"Message of Hope"
#dir_array[scpm]="scpm" #"Someone Cares Prison Ministry"
#dir_array[stb]="stb" #"Sink The Beagle"

declare -A s3_show_dir_array
## The values in this array can be used to alter the directory names in the S3 Dest URL for each show 

## Chip and Healthy by Choice files are to be slightly re-arranged at the time of upload
## converted has /hbc and /hbc/chip_health
## on upload those should become /chip/(containing hbc*.mp3) and /chip/(chip*.mp3 from chip_health)
s3_show_dir_array[hbc]="chip" # "Healthy by Choice" files are moved to chip
s3_show_dir_array[chip]="chip" # "CHIP Health" filed moved out of chip_health into parent

s3_show_dir_array[ail]="ail" #"American Indian Living"
s3_show_dir_array[bt]="bt" #"Bible Talk"
s3_show_dir_array[ec]="ec" #"Education Currents"
s3_show_dir_array[hal]="hnl" #"Health and Longevity"
s3_show_dir_array[hm]="hw" #"Heartwise Ministries"
s3_show_dir_array[hc]="hsc" #"Homeschool Companion"
s3_show_dir_array[lqa]="lq" #"LifeQuest - Authors"
s3_show_dir_array[lql]="lql" #"LifeQuest Liberty"
s3_show_dir_array[moh]="moh" #"Message of Hope"
s3_show_dir_array[stb]="sb" #"Sink The Beagle"
s3_show_dir_array[scpm]="scpm" #"Someone Cares Prison Ministry"

declare -A  s3_file_name_array
## placeholder for later function pulling ls from s3
## made associative for faster searching

skip_file() {
    # Arguments:
    # $1 -> $src_file
    # $2 -> $skipped_reason
    #    one of: src not found | dest exists | bad filename | bad filetype
    src_file="$1"
    skipped_reason="$2"
    #echo "skip_file()"

    #echo "Skipping..."
    echo "[$skipped_reason] $src_file"  >>  "$skipped_file"

}

test_year() {
    logfile="/var/projects/ltr_podcasts/scripts/logs/upload-podcasts"
    # Arguments:
    # $1 -> test_date

    file_date="$1"
    cur_year="$(date +%Y)"
    tag_year=''

    if [[ -z "$file_date" ]]; then
        echo "received: $file_date. Apparently empty. Setting cur_year" >> $logfile 2>&1
        received="BAD"
        tag_year="$cur_year"
    else
        if [[ ${#file_date} -lt 4 ]]; then
            echo "received: $file_date. Too short. Setting cur_year" >> $logfile 2>&1
            received="BAD"
            tag_year=$"cur_year"
        else
            snip_four="$(echo "${file_date:0:4}")"
            if ! [[ "$snip_four" =~ ^[0-9]{4}$ ]]; then
                echo "took: $snip_four. Not digits. Setting cur_year" >> $logfile 2>&1
                received="BAD"
                tag_year="$cur_year"
            else
                first_char="$(echo "${snip_four:0:1}")"
                second_char="$(echo "${snip_four:1:1}")"
                third_char="$(echo "${snip_four:2:1}")"
                fourth_char="$(echo "${snip_four:3:1}")"
                case "$first_char" in
                    2)
                        if [[ "$second_char" =~ ^[^0]$ ]]; then
                            echo "received: 2${second_char}XX. ${second_char} is invalid. Setting cur_year" >> $logfile 2>&1
                            received="BAD"
                            tag_year="$cur_year"
                        else
                            if [[ "$third_char" =~ ^[1]$ ]]; then
                                if [[ "$fourth_char" =~ ^[^0-8]$ ]]; then
                                    echo "received: 2${second_char}${third_char}${fourth_char}. ${fourth_char} is invalid year. Setting cur_year" >> $logfile 2>&1
                                    received="BAD"
                                    tag_year="$cur_year"
                                else
                                    tag_year="$snip_four"
                                    received="GOOD"
                                fi
                            elif [[ "$third_char" =~ ^[^0]$ ]]; then
                                    echo "received: 2${second_char}${third_char}X. ${third_char} is invalid. Setting cur_year" >> $logfile 2>&1
                                    received="BAD"
                                    tag_year="$cur_year"
                            else
                                tag_year="$snip_four"
                                received="GOOD"
                            fi
                        fi
                        ;;
                    ## Uncomment these lines if we need to accept years before 2000
                    #1) 
                    #    echo "PASSED: first_char is 1 -> ${first_char}." >> $logfile
                    #    if [[ "$second_char" =~ ^[^8-9]$ ]]; then
                    #        echo "received 1${second_char}XX. ${second_char} is invalid. Setting cur_year" >> $logfile 2>&1
                    #        received="BAD"
                    #        tag_year="$cur_year"
                    #    else
                    #        tag_year="$snip_four"
                    #        received="GOOD"
                    #    fi
                    #    ;;
                    *)
                        echo "received: ${first_char}XXX. ${first_char} is invalid. Setting cur_year" >> $logfile 2>&1
                        received="BAD"
                        tag_year="$cur_year"
                        ;;
                esac
            fi
        fi
    fi

    echo "$tag_year"
}

get_year() {
    ## Retrieve a date string from the ID3 tags
    # Arguments:
    # $1 -> src_file
    eyeD3_return=$(eyeD3 --log-level error "$src_file")
    date_from_file="$(echo "$eyeD3_return" | grep date | tr -d ' ' | awk 'BEGIN{FS=OFS=":"}{ print $2 }')"
    echo "$date_from_file" 

}

compose_upload_path() {
    # Arguments:
    # $1 -> src_file
    # $2 -> s3_show)dir
    # $3 -> file_year

    src_file="$1"
    s3_show_dir="$2"
    file_year="$3"

    file_name="$(echo "$src_file" | awk 'BEGIN{FS=OFS="/"}{ print $(NF) }')"
    #echo -e "\n$src_file\n$s3_show_dir\n$file_year"

    s3parts="ltrpodcasts"
    upload_path="${s3parts}/${s3_show_dir}/${file_year}/${file_name}"
    echo "$upload_path"
}


upload_files() {
    # Arguments:
    # 1 -> src_dir
    # 2 -> key
    src_dir="$1"
    key="$2"

    show_dir_on_s3="${s3_show_dir_array[$key]}"

    s3_file_list="s3_file_list_${key}"

    if [[ -f $s3_file_list ]]; then
        echo "$s3_file_list found. Removing"
        rm "$s3_file_list"
    fi

    touch s3_file_list || echo "failed to create $s3_file_list" >> $logfile
    
    ## pulling a file list from aws
    aws s3 ls s3://ltrpodcasts/${show_dir_on_s3} --recursive > $s3_file_list 2>$logfile
    
    mycount=0
    while IFS= read -r line; do
        s3_file_name="$(echo "$line" | awk 'BEGIN{FS=OFS="/"}{ print $(NF) }')"

        s3_file_name_array[${s3_file_name}]="${mycount}"
        (( mycount++ ))

    done < "$s3_file_list"

    find "$src_dir" -type f -print0 |
      while IFS= read -r -d $'\0' src_file; do

        file_name="$(echo "$src_file" | awk 'BEGIN{FS=OFS="/"}{ print $(NF) }')"

        ## returns exit 0 if the array key as a non-zero sized element 
        ## if the array key has been created above 
        ## the filename existed in the list pulled from ls
        ## if the key exists, the file is already on s3
        ##    [[ -n "${s3_file_name_array["$file_name"]}" ]] && printf '%sfound\n' "$i"

        if [[ -n "${s3_file_name_array["$file_name"]}" ]]; then
            skip_file "$src_file" "exists on s3"
        else

            ## retrieve date info from id3 tag
            date_from_file="$(get_year "$src_file")"

            ## use id3 tag date to get a valid year
            file_year="$(test_year "$date_from_file")"

            upload_path="$(compose_upload_path "$src_file" "${s3_show_dir_array[$key]}" "$file_year")"
            echo "$upload_path"

            ##  adding here s3://
            modded_upload_path="s3://${upload_path}"
            

            ## testing. Without this aws line, nothing gets uploaded
            aws s3 cp --only-show-errors "$src_file" "$modded_upload_path" >> "$logfile"

            aws_cmd_exit_status="$?"

            site_hostname="https://s3.us-east-2.amazonaws.com"
            url_for_output="${site_hostname}/${upload_path}"

            if [[ $aws_cmd_exit_status == 0 ]]; then
                echo "aws success: $src_file" >> $logfile
                echo "${src_file},${url_for_output}" >> "$uploaded_file"
            else 
                echo "aws failed : $aws_cmd_exit_status : $src_file" >> $logfile
            fi
        fi


      done

      rm "$s3_file_list"
}

main() {
    ## Dumps the list of directories into the logfile
    #for key in "${!dir_array[@]}"; do
#        src_dir="${dir_array[$key]}"
#        src_dir="$converted_dir/$src_dir"
#    done

    ## Processes each directory
    for key in "${!dir_array[@]}"; do

        uploaded_file="${logs_dir}/uploaded_${key}"

        if [[ -f "$uploaded_file" ]]; then
            mv "$uploaded_file" "${uploaded_file}_$(date +%Y%m%d_%H%M)"
        fi

        touch "$uploaded_file"

        echo -e "**** $(date +%Y%m%d_%H%M) ****" >> "$uploaded_file"

        skipped_file="${logs_dir}/skipped_${key}"
        if [[ -f "$skipped_file" ]]; then
            mv "$skipped_file" "${skipped_file}_$(date +%Y%m%d_%H%M)"
        fi
        touch "$skipped_file"
        echo -e "**** $(date +%Y%m%d_%H%M) ****" >> "$skipped_file"

        ## testing log file with no key
        #logfile="${logs_dir}/${script_name}"
        logfile="${logs_dir}/${script_name}_${key}"

        if [[ -f "$logfile" ]]; then
            rm "$logfile"
        fi
        touch $logfile

        echo -e "**** $(date +%Y%m%d_%H%M) ****" >> "$logfile"

        src_dir="${dir_array[$key]}"

        echo "$src_dir" >> "$logfile"
        echo -e "**** $(date +%Y%m%d_%H%M) ****" >> "$logfile"
        echo -e "**** Start of script ****" >> "$logfile"
        echo -e "Looking at these source directories:" >> "$logfile"

        src_dir="$converted_dir/$src_dir"

        if [[ -d "$src_dir" ]]; then
            #echo "main() - src_dir is $src_dir";

           upload_files "$src_dir" "$key";

        else
            echo "main() - scr_dir as ''$src_dir'' is not valid"
        fi
    done

}

main

#echo "**** logfile ****"
#cat $logfile
